apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.slack.secretName }}
  labels:
    {{- include "sentria.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.slack.secretKey }}: {{ .Values.slack.webhookUrl | default "https://hooks.slack.com/services/PLACEHOLDER/SENTRIA/WEBHOOK" | quote }}
